# Load the contingency table with two variables from the xlsx file

In [2]:
import pandas as pd 
from pandas import read_excel
from math import sqrt
import numpy as np

my_sheet = 'Feuil1'
file_name = 'data_metrics.xlsx' 
df = read_excel(file_name, sheet_name = my_sheet)
display(df)

      AB   -AB     A-B    -A-B
0  10000  1000    1000  100000
1  10000  1000    1000     100
2    100  1000    1000  100000
3   1000  1000    1000  100000
4   1000   100   10000  100000
5   1000    10  100000  100000

In [2]:
df["Lift"] = np.nan
df["Chi2"] = np.nan
df["Cosine"] = np.nan
df["Kulczynski"] = np.nan

# Define functions to compute the lift and the X2 metrics

In [5]:
def compute_Lift(row):
    total_1 = row['AB'] + row['A-B']
    total_2 = row['-AB'] + row['-A-B']
    total_3 = row['AB'] + row['-AB']
    total_4 = row['A-B'] + row['-A-B']
    if (total_1 + total_2) == (total_3 + total_4):
        total = total_1 + total_2
        lift = (row['AB']/total)/((total_1/total)*(total_3/total))
        return lift
    
def compute_Chi2(row):
    total_1 = row['AB'] + row['A-B']
    total_2 = row['-AB'] + row['-A-B']
    total_3 = row['AB'] + row['-AB']
    total_4 = row['A-B'] + row['-A-B']
    if (total_1 + total_2) == (total_3 + total_4):
        total = total_1 + total_2
        r1 = total_1 / (total_1 + total_2)
        r2 = total_2 / (total_1 + total_2)
        chi2 = (((row['AB']-(r1*total_3)))**2)/(r1*total_3) + (((row['A-B']-(r1*total_4)))**2)/(r1*total_4) + (((row['-AB']-(r2*total_3)))**2)/(r2*total_3) + (((row['-A-B']-(r2*total_4)))**2)/(r2*total_4)  
        return chi2
    
def compute_Cosine(row):
    total_1 = row['AB'] + row['A-B']
    total_2 = row['-AB'] + row['-A-B']
    total_3 = row['AB'] + row['-AB']
    total_4 = row['A-B'] + row['-A-B']
    if (total_1 + total_2) == (total_3 + total_4):
        total = total_1 + total_2
        cosine = (row['AB']/total)/sqrt(((total_1/total)*(total_3/total)))
        return cosine
    
def compute_Kulczynski(row):
    total_1 = row['AB'] + row['A-B']
    total_2 = row['-AB'] + row['-A-B']
    total_3 = row['AB'] + row['-AB']
    total_4 = row['A-B'] + row['-A-B']
    if (total_1 + total_2) == (total_3 + total_4):
        total = total_1 + total_2
        Kulczynski = ((row['AB']/total)/2)*((1/(total_1/total)) + (1/(total_3/total)))
        return Kulczynski

# Results

In [6]:
for index, row in df.iterrows():
    lift = compute_Lift(row)
    chi2 = compute_Chi2(row)
    cosine = compute_Cosine(row)
    Kulczynski = compute_Kulczynski(row)
    df.loc[index,'Lift'] = lift
    df.loc[index,'Chi2'] = chi2
    df.loc[index,'Cosine'] = cosine
    df.loc[index,'Kulczynski'] = Kulczynski
display(df)

      AB   -AB     A-B    -A-B       Lift          Chi2    Cosine  Kulczynski
0  10000  1000    1000  100000   9.256198  90556.761167  0.909091    0.909091
1  10000  1000    1000     100   1.000000      0.000000  0.909091    0.909091
2    100  1000    1000  100000   8.438017    670.012096  0.090909    0.090909
3   1000  1000    1000  100000  25.750000  24740.295069  0.500000    0.500000
4   1000   100   10000  100000   9.181818   8172.827173  0.287480    0.500000
5   1000    10  100000  100000   1.970493    965.543584  0.099010    0.500000

# Discussion
- LIFT :
    - lift > 1 : A and B appear more often together that we would have expected. The presence of B has a positive effect on the presence of A.
    - lift < 1 : A and B appear less often together that one would have expected which means that the rule is useless or , in other words, that the presence of B has a negative effect on the presence of A.

- Chi2 (or X2):
    - Chi2 = 0: independent
    - Chi2 > 0: correlated, positively or negatively (supplementary test necessary)